package org.netvogue.ecommerce.domain.model;

public enum OrderStatus {
  APPROVAL_PENDING_FROM_BRAND, APPROVED_BY_BRAND, APPROVAL_PENDING_FROM_BOTIQUE, APPROVED_BY_BOTIQUE, CANCELLED_BY_BRAND, CANCELLED_BY_BOTIQUE, REVIEWED_BY_BRAND;
}
